name: Deploy LedgerFlow Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

permissions:
  id-token: write
  contents: read

jobs:
  deploy-infra:
    name: Deploy Bicep Infrastructure
    runs-on: ubuntu-latest

    env:
      LOCATION: eastus
      APP_NAME: LedgerFlow

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Validate Bicep
        run: |
          az bicep build \
            --file infra/bicep/main.bicep

      - name: Deploy Infrastructure
        run: |
          az deployment sub create \
            --location ${{ env.LOCATION }} \
            --template-file infra/bicep/main.bicep \
            --parameters \
              environment=${{ inputs.environment }} \
              appName=${{ env.APP_NAME }}
