// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZFinance.Core;

#nullable disable

namespace ZFinance.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260113141644_v1.0.0")]
    partial class v100
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActionsRoles", b =>
                {
                    b.Property<long>("ActionID")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleID")
                        .HasColumnType("bigint");

                    b.HasKey("ActionID", "RoleID");

                    b.HasIndex("RoleID");

                    b.ToTable("RolesActions", "Security");
                });

            modelBuilder.Entity("MenusRoles", b =>
                {
                    b.Property<long>("MenuID")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleID")
                        .HasColumnType("bigint");

                    b.HasKey("MenuID", "RoleID");

                    b.HasIndex("RoleID");

                    b.ToTable("RolesMenus", "Security");
                });

            modelBuilder.Entity("RolesUsers", b =>
                {
                    b.Property<long>("RoleID")
                        .HasColumnType("bigint");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("RoleID", "UserID");

                    b.HasIndex("UserID");

                    b.ToTable("RolesUsers", "Security");
                });

            modelBuilder.Entity("ZFinance.Core.Entities.Audit.OperationsHistory", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long?>("EntityID")
                        .HasColumnType("bigint");

                    b.Property<string>("EntityName")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperationType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ServiceHistoryID")
                        .HasColumnType("bigint");

                    b.Property<string>("TableName")
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("ID");

                    b.HasIndex("ServiceHistoryID");

                    b.ToTable("OperationsHistory", "Audit");
                });

            modelBuilder.Entity("ZFinance.Core.Entities.Audit.ServicesHistory", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long>("ChangedByID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ChangedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ID");

                    b.HasIndex("ChangedByID");

                    b.ToTable("ServicesHistory", "Audit");
                });

            modelBuilder.Entity("ZFinance.Core.Entities.Security.Actions", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(150)");

                    b.Property<long>("CreatedByID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Entity")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long>("LastChangedByID")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastChangedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("VARCHAR(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("ID");

                    b.HasIndex("CreatedByID");

                    b.HasIndex("LastChangedByID");

                    b.ToTable("Actions", "Security");
                });

            modelBuilder.Entity("ZFinance.Core.Entities.Security.Menus", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long>("CreatedByID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Label")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<long>("LastChangedByID")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastChangedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<long?>("ParentMenuID")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("URL")
                        .HasColumnType("VARCHAR(200)");

                    b.HasKey("ID");

                    b.HasIndex("CreatedByID");

                    b.HasIndex("LastChangedByID");

                    b.HasIndex("ParentMenuID");

                    b.ToTable("Menus", "Security");
                });

            modelBuilder.Entity("ZFinance.Core.Entities.Security.RefreshTokens", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("RefreshTokens", "Security");
                });

            modelBuilder.Entity("ZFinance.Core.Entities.Security.Roles", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long>("CreatedByID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long>("LastChangedByID")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastChangedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("VARCHAR(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("ID");

                    b.HasIndex("CreatedByID");

                    b.HasIndex("LastChangedByID");

                    b.ToTable("Roles", "Security");
                });

            modelBuilder.Entity("ZFinance.Core.Entities.Security.Users", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long>("CreatedByID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("VARCHAR(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long>("LastChangedByID")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastChangedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("ID");

                    b.HasIndex("CreatedByID");

                    b.HasIndex("LastChangedByID");

                    b.ToTable("Users", "Security");
                });

            modelBuilder.Entity("ActionsRoles", b =>
                {
                    b.HasOne("ZFinance.Core.Entities.Security.Actions", null)
                        .WithMany()
                        .HasForeignKey("ActionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ZFinance.Core.Entities.Security.Roles", null)
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("MenusRoles", b =>
                {
                    b.HasOne("ZFinance.Core.Entities.Security.Menus", null)
                        .WithMany()
                        .HasForeignKey("MenuID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ZFinance.Core.Entities.Security.Roles", null)
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("RolesUsers", b =>
                {
                    b.HasOne("ZFinance.Core.Entities.Security.Roles", null)
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ZFinance.Core.Entities.Security.Users", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("ZFinance.Core.Entities.Audit.OperationsHistory", b =>
                {
                    b.HasOne("ZFinance.Core.Entities.Audit.ServicesHistory", "ServiceHistory")
                        .WithMany("Operations")
                        .HasForeignKey("ServiceHistoryID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ServiceHistory");
                });

            modelBuilder.Entity("ZFinance.Core.Entities.Audit.ServicesHistory", b =>
                {
                    b.HasOne("ZFinance.Core.Entities.Security.Users", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedByID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChangedBy");
                });

            modelBuilder.Entity("ZFinance.Core.Entities.Security.Actions", b =>
                {
                    b.HasOne("ZFinance.Core.Entities.Security.Users", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ZFinance.Core.Entities.Security.Users", "LastChangedBy")
                        .WithMany()
                        .HasForeignKey("LastChangedByID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("LastChangedBy");
                });

            modelBuilder.Entity("ZFinance.Core.Entities.Security.Menus", b =>
                {
                    b.HasOne("ZFinance.Core.Entities.Security.Users", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ZFinance.Core.Entities.Security.Users", "LastChangedBy")
                        .WithMany()
                        .HasForeignKey("LastChangedByID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ZFinance.Core.Entities.Security.Menus", "ParentMenu")
                        .WithMany("ChildMenus")
                        .HasForeignKey("ParentMenuID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedBy");

                    b.Navigation("LastChangedBy");

                    b.Navigation("ParentMenu");
                });

            modelBuilder.Entity("ZFinance.Core.Entities.Security.RefreshTokens", b =>
                {
                    b.HasOne("ZFinance.Core.Entities.Security.Users", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZFinance.Core.Entities.Security.Roles", b =>
                {
                    b.HasOne("ZFinance.Core.Entities.Security.Users", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ZFinance.Core.Entities.Security.Users", "LastChangedBy")
                        .WithMany()
                        .HasForeignKey("LastChangedByID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("LastChangedBy");
                });

            modelBuilder.Entity("ZFinance.Core.Entities.Security.Users", b =>
                {
                    b.HasOne("ZFinance.Core.Entities.Security.Users", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ZFinance.Core.Entities.Security.Users", "LastChangedBy")
                        .WithMany()
                        .HasForeignKey("LastChangedByID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("LastChangedBy");
                });

            modelBuilder.Entity("ZFinance.Core.Entities.Audit.ServicesHistory", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("ZFinance.Core.Entities.Security.Menus", b =>
                {
                    b.Navigation("ChildMenus");
                });

            modelBuilder.Entity("ZFinance.Core.Entities.Security.Users", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
